# Generated by Django 5.2.3 on 2025-07-31 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=255, unique=True)),
                ('temporary_domain', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(editable=False)),
                ('expiration_date', models.DateTimeField()),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_token', to='institution.institution')),
            ],
        ),
    ]
