# Generated by Django 5.2 on 2025-05-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='tax_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
