# Generated by Django 5.2.3 on 2025-07-26 21:15

import django.db.models.deletion
import document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=document.models.directory_path)),
                ('ipfs_cid', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_date', models.DateTimeField(editable=False)),
                ('update_date', models.DateTimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='institution.institution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='subject.subject')),
            ],
        ),
    ]
