# Generated by Django 5.2.1 on 2025-06-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ipfs_cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
